### ISSUE TITLE
App Crash beim öffnen der Einstellungen

### ISSUE THREAD

**Issue by Flohkiste** [GastroGo/Orga#52]

**Comment by Flohkiste** [comment]
Error: 
2024-05-30 09:43:37.116 29595-29595 AndroidRuntime          com.example.login                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.login, PID: 29595
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.login/com.example.login.Settings}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:112)
                                                                                                    	at android.os.Looper.loop(Looper.java:216)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7625)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                                                                    	at com.example.login.Settings.loadModelData(Settings.java:175)
                                                                                                    	at com.example.login.Settings.onCreate(Settings.java:99)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7458)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7448)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:112) 
                                                                                                    	at android.os.Looper.loop(Looper.java:216) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7625) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
                                                                                                    	
                                                                                                    	
                                                                                                    	
                                                                              

https://github.com/GastroGo/Orga/assets/76181281/d9d810cc-c7de-4620-8e8c-95f12316f7f6
