### ISSUE TITLE
Komischer Bug wenn Mitarbeiter gelöscht wird, nachdem man auf einen draufgeklickt hat

### ISSUE THREAD

**Issue by mt1nr** [GastroGo/Orga#57]
[Screen_recording_20240529_125447.webm](https://github.com/GastroGo/Orga/assets/130224348/b9982516-39dd-4df1-824e-0dc97669f674)

Error Message:
  E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.example.login, PID: 885
                                                                                                    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.example.employeemanager.EmployeeItem.name' on a null object reference in method 'void com.example.employeemanager.Employee$1.onDataChange(com.google.firebase.database.DataSnapshot)'
                                                                                                    	at com.example.employeemanager.Employee$1.onDataChange(Employee.java:69)
                                                                                                    	at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
                                                                                                    	at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
                                                                                                    	at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by SchaefferSil** [comment]
Kann ich nicht reproduzieren
